version: '3'

services:

  redis-0:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly yes", "--cluster-enabled yes", "--loglevel verbose"]
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes: 
      - ./redisdata0:/data

  redis-1:
    image: redis:latest
    restart: always
    ports:
      - 6380:6379
    command: ["redis-server", "--appendonly yes", "--cluster-enabled yes", "--loglevel verbose"]
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes: 
      - ./redisdata1:/data

  postgresql:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/pgdata
    volumes:
      - ./setup_schema.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pgdata:/pgdata

  webapp:
    depends_on:
      - postgresql
    build:
      context: ./webapp
      dockerfile: Dockerfile
    image: ack-rds-gitops-workshop/webapp:2.0
    ports:
      - 8443:8443
    volumes:
      - ./appdata:/appdata
    environment:
      - DATABASE_HOST=host.docker.internal
      - DATABASE_RO_HOST=host.docker.internal
      - ECHOST=host.docker.internal:11211
      - DATABASE_PORT=5432
      - DATABASE_USER=dbuser1
      - DATABASE_PASSWORD=eksackdemo
      - DATABASE_DB_NAME=eksackdemo
      - PRODUCTS_SERVICE=http://host.docker.internal:8444
      - USER_SERVICE=http://host.docker.internal:8446
      - ORDER_SERVICE=http://host.docker.internal:8448
      - KART_SERVICE=http://host.docker.internal:8445

  product:
    depends_on:
      - postgresql
    build:
      context: ./product
      dockerfile: Dockerfile
    image: ack-rds-gitops-workshop/product:2.0
    ports:
      - 8444:8444
    environment:
      - DATABASE_HOST=host.docker.internal
      - DATABASE_RO_HOST=host.docker.internal
      - DATABASE_PORT=5432
      - DATABASE_USER=dbuser1
      - DATABASE_PASSWORD=eksackdemo
      - DATABASE_DB_NAME=eksackdemo

  user:
    depends_on:
      - postgresql
    build:
      context: ./user
      dockerfile: Dockerfile
    image: ack-rds-gitops-workshop/user:2.0
    ports:
      - 8446:8446
    environment:
      - DATABASE_HOST=host.docker.internal
      - DATABASE_RO_HOST=host.docker.internal
      - DATABASE_PORT=5432
      - DATABASE_USER=dbuser1
      - DATABASE_PASSWORD=eksackdemo
      - DATABASE_DB_NAME=eksackdemo
      - MEMDB_HOST=host.docker.internal
      - MEMDB_PORT=6379
      - MEMDB_PASS=krishna

  order:
    depends_on:
      - postgresql
    build:
      context: ./order
      dockerfile: Dockerfile
    image: ack-rds-gitops-workshop/order:2.0
    ports:
      - 8448:8448
    environment:
      - DATABASE_HOST=host.docker.internal
      - DATABASE_RO_HOST=host.docker.internal
      - DATABASE_PORT=5432
      - DATABASE_USER=dbuser1
      - DATABASE_PASSWORD=eksackdemo
      - DATABASE_DB_NAME=eksackdemo

  kart:
    depends_on:
      - postgresql
    build:
      context: ./kart
      dockerfile: Dockerfile
    image: ack-rds-gitops-workshop/kart:2.0
    ports:
      - 8445:8445
    environment:
      - DATABASE_HOST=host.docker.internal
      - DATABASE_RO_HOST=host.docker.internal
      - DATABASE_PORT=5432
      - DATABASE_USER=dbuser1
      - DATABASE_PASSWORD=eksackdemo
      - DATABASE_DB_NAME=eksackdemo
