apiVersion: aws.database.example.org/v1alpha1
kind: CrossplaneAPGServerless
metadata:
  name: crossplane-apg-serverless
spec:
  databaseName: mydb
  subnetIds:
   - <dbSubnetId1>
   - <dbSubnetId2>
   - <dbSubnetId3>
  region: <region>
  vpcId: <vpcSecurityGroupIDs>
  cidrBlocks: 
   - "<cidrBlock>"
  engine: aurora-postgresql
  port: 5432
  instanceClass: db.serverless
  maxCapacity: 4
  minCapacity: 0.5
  engineVersion: "13.7"
  masterUsername: adminer
  masterPasswordSecret:  <db-creds>
  connectionInfoSecret: asv2-db-instance-conn
  namespace: retailapp
  resourceConfig:
    providerConfigName: default 
