apiVersion: aws.database.example.org/v1alpha1
kind: CrossplaneMemoryDB
metadata:
  name: retailapp-memorydb
spec:
  subnetIds:
   - <memorydbSubnetId1>
   - <memorydbSubnetId1>
   - <memorydbSubnetId1>
  region: <region>
  vpcId: <vpcID>
  cidrBlocks: 
   -  "<cidrBlock>"
  port: 6379
  instanceClass: "db.t4g.small"
  connectionInfoSecret: memorydb-cluster-conn-s
  connectionInfoCM: memorydb-cluster-conn-cm
  namespace: retailapp
  name: retailapp-memorydb
  resourceConfig:
    providerConfigName: provider-aws
