apiVersion: apps/v1
kind: Deployment
metadata:
  name: kart
  namespace: retailapp
  labels:
    app: eksack
    service: kart
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  selector:
    matchLabels:
      app: eksack
      service: kart
  template:
    metadata:
      labels:
        app: eksack
        service: kart
    spec:
      restartPolicy: Always
      containers:
      - name: kart
        image: 635309892211.dkr.ecr.us-east-2.amazonaws.com/eksack/kart:1.0
        imagePullPolicy: Always
        ports:
         - containerPort: 8445
        env:
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                 name: db-creds-out-serverless
                 key: endpoint
          - name: DATABASE_PORT
            value: "5432"
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: database_user
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: database_password
          - name: DATABASE_DB_NAME
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: database_db_name
          - name: DATABASE_RODB_NAME
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: database_rodb_name
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: secret_key
          - name: AUTHTOKEN
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: authtoken
          - name: MEMDB_HOST
            valueFrom:
              configMapKeyRef:
                 name: memorydb-cluster-conn-cm
                 key: memorydb-cluster-host
          - name: MEMDB_PORT
            valueFrom:
              configMapKeyRef:
                 name: memorydb-cluster-conn-cm
                 key: memorydb-cluster-port
          - name: MEMDB_USER
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: memdb_user
          - name: MEMDB_PASS
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: memdb_pass
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: retailapp
  labels:
    app: eksack
    service: product
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  selector:
    matchLabels:
      app: eksack
      service: product
  template:
    metadata:
      labels:
        app: eksack
        service: product
    spec:
      restartPolicy: Always
      containers:
      - name: product
        image: 635309892211.dkr.ecr.us-east-2.amazonaws.com/eksack/product:1.0
        imagePullPolicy: Always
        ports:
         - containerPort: 8444
        env:
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                 name: db-creds-out-serverless
                 key: endpoint
          - name: DATABASE_PORT
            value: "5432"
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: database_user
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: database_password
          - name: DATABASE_DB_NAME
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: database_db_name
          - name: DATABASE_RODB_NAME
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: database_rodb_name
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: secret_key
          - name: AUTHTOKEN
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: authtoken
          - name: MEMDB_HOST
            valueFrom:
              configMapKeyRef:
                 name: memorydb-cluster-conn-cm
                 key: memorydb-cluster-host
          - name: MEMDB_PORT
            valueFrom:
              configMapKeyRef:
                 name: memorydb-cluster-conn-cm
                 key: memorydb-cluster-port
          - name: MEMDB_USER
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: memdb_user
          - name: MEMDB_PASS
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: memdb_pass
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: retailapp
  labels:
    app: eksack
    service: user
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  selector:
    matchLabels:
      app: eksack
      service: user
  template:
    metadata:
      labels:
        app: eksack
        service: user
    spec:
      restartPolicy: Always
      containers:
      - name: user
        image: 635309892211.dkr.ecr.us-east-2.amazonaws.com/eksack/user:1.0
        imagePullPolicy: Always
        ports:
         - containerPort: 8446
        env:
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                 name: db-creds-out-serverless
                 key: endpoint
          - name: DATABASE_PORT
            value: "5432"
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: database_user
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: database_password
          - name: DATABASE_DB_NAME
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: database_db_name
          - name: DATABASE_RODB_NAME
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: database_rodb_name
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: secret_key
          - name: AUTHTOKEN
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: authtoken
          - name: MEMDB_HOST
            valueFrom:
              configMapKeyRef:
                 name: memorydb-cluster-conn-cm
                 key: memorydb-cluster-host
          - name: MEMDB_PORT
            valueFrom:
              configMapKeyRef:
                 name: memorydb-cluster-conn-cm
                 key: memorydb-cluster-port
          - name: MEMDB_USER
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: memdb_user
          - name: MEMDB_PASS
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: memdb_pass
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: retailapp
  labels:
    app: eksack
    service: webapp
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: eksack
      service: webapp
  template:
    metadata:
      labels:
        app: eksack
        service: webapp
    spec:
      restartPolicy: Always
      containers:
      - name: webapp
        image: 635309892211.dkr.ecr.us-east-2.amazonaws.com/eksack/webapp:1.0
        imagePullPolicy: Always
        ports:
         - containerPort: 8443
        env:
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                 name: db-creds-out-serverless
                 key: endpoint
          - name: DATABASE_PORT
            value: "5432"
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: database_user
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: database_password
          - name: DATABASE_DB_NAME
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: database_db_name
          - name: DATABASE_RODB_NAME
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: database_rodb_name
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: secret_key
          - name: AUTHTOKEN
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: authtoken
          - name: PRODUCTS_SERVICE
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: product_service
          - name: KART_SERVICE
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: kart_service
          - name: USER_SERVICE
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: user_service
          - name: ORDER_SERVICE
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: order_service
          - name: MEMDB_HOST
            valueFrom:
              configMapKeyRef:
                 name: memorydb-cluster-conn-cm
                 key: memorydb-cluster-host
          - name: MEMDB_PORT
            valueFrom:
              configMapKeyRef:
                 name: memorydb-cluster-conn-cm
                 key: memorydb-cluster-port
          - name: MEMDB_USER
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: memdb_user
          - name: MEMDB_PASS
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: memdb_pass
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  namespace: retailapp
  labels:
    app: eksack
    service: order
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
  selector:
    matchLabels:
      app: eksack
      service: order
  template:
    metadata:
      labels:
        app: eksack
        service: order
    spec:
      restartPolicy: Always
      containers:
      - name: order
        image: 635309892211.dkr.ecr.us-east-2.amazonaws.com/eksack/order:1.0
        imagePullPolicy: Always
        ports:
         - containerPort: 8448
        env:
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                 name: db-creds-out-serverless
                 key: endpoint
          - name: DATABASE_PORT
            value: "5432"
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: database_user
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: database_password
          - name: DATABASE_DB_NAME
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: database_db_name
          - name: DATABASE_RODB_NAME
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: database_rodb_name
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: secret_key
          - name: AUTHTOKEN
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: authtoken
          - name: MEMDB_HOST
            valueFrom:
              configMapKeyRef:
                 name: memorydb-cluster-conn-cm
                 key: memorydb-cluster-host
          - name: MEMDB_PORT
            valueFrom:
              configMapKeyRef:
                 name: memorydb-cluster-conn-cm
                 key: memorydb-cluster-port
          - name: MEMDB_USER
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: memdb_user
          - name: MEMDB_PASS
            valueFrom:
              secretKeyRef:
                 name: eksack-secret
                 key: memdb_pass
