apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ack-memorydb-controller
  namespace: flux-system
spec:
  releaseName: memorydb-chart
  chart:
    spec:
      chart: memorydb-chart
      version: v0.0.2
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ack-source
        namespace: flux-system
  interval: 1m0s
  install:
    remediation:
      retries: 3
  values:
    serviceAccount:
      create: false
    aws:
      region: <region>
