apiVersion: aws.database.example.org/v1alpha1
kind: CrossplaneAPGServerless
metadata:
  name: crossplane-apg-serverless
spec:
  databaseName: mydb
  subnetIds:
   - subnet-069d1f7af36af5805
   - subnet-0a299a68711fa9bf1
   - subnet-0390461672822b765
  region: us-east-2
  vpcId: vpc-0394aecf1a99670d0
  cidrBlocks: 
   - "10.40.0.0/16"
  engine: aurora-postgresql
  port: 5432
  instanceClass: db.serverless
  maxCapacity: 4
  minCapacity: 0.5
  engineVersion: "13.7"
  masterUsername: adminer
  masterPasswordSecret:  db-creds
  connectionInfoSecret: db-creds-out-serverless
  namespace: default
  resourceConfig:
    providerConfigName: default 
