apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcrossplanepgs.aws.database.example.org
spec:
  defaultCompositionRef: 
    name: rds-postgres.aws.database.example.org
  group: aws.database.example.org
  names:
    kind: XCrossplanePg
    plural: xcrossplanepgs
  claimNames:
    kind: CrossplanePG
    plural: crossplanepgs
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                databaseName:
                  type: string
                storageGB:
                  type: integer
                secret:
                  type: string
                resourceConfig:
                  description: ResourceConfig defines general properties of this AWS
                    resource.
                  properties:
                    providerConfigName:
                      type: string
                  type: object
              required:
              - secret
              - databaseName
              - storageGB
