apiVersion: aws.database.example.org/v1alpha1
kind: CrossplaneMemoryDB
metadata:
  name: crossplane-memorydb
spec:
  subnetIds:
   - subnet-01d3ca48574e195c7
   - subnet-0da0eab947e2cce05
   - subnet-01cce3b7adbf16729
  region: us-east-2
  cidrBlocks: 
   - "10.40.0.0/16"
  port: 6379
  instanceClass: db.t4g.small
  connectionInfoSecret: memorydb-creds-out
  connectionInfoCM: memorydb-creds-out-cm
  namespace: default
  name: retailapp-memorydb
  resourceConfig:
    providerConfigName: default 
