apiVersion: aws.database.example.org/v1alpha1
kind: CrossplaneAuroraPG
metadata:
  name: crossplane-aurora-pg
spec:
  databaseName: mydb
  subnetIds:
   - subnet-0089d29b20ed2f304
   - subnet-0394f290a15c8ec51
   - subnet-0eca40cf17df43c21
  region: us-east-2
  vpcId: vpc-022259b88c391c9de
  cidrBlocks: 
   - "10.40.0.0/16"
  engine: aurora-postgresql
  instanceClass: db.serverless
  serverlessv2ScalingConfiguration:
   - maxCapacity: 4 
     minCapacity: 0.5
  engineVersion: "13.7"
  masterUsername: adminer
  masterPasswordSecret:  db-creds
  connectionInfoSecret: db-creds-out
  namespace: default
  resourceConfig:
    providerConfigName: default 
