apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: foobar1
spec:
  forProvider:
    manifest:
      apiVersion: v1
      stringData:
        endpoint: to-be-patched
      kind: Secret
      type: Opaque
      metadata:
        namespace: default
  providerConfigRef:
    name: provider-k8s
  references:
    - patchesFrom:
        apiVersion: memorydb.aws.upbound.io/v1beta1
        fieldPath: status.atProvider.clusterEndpoint[0].address
        kind: Cluster
        name: crossplane-memorydb-9j89x-fzxx7
        namespace: default
      toFieldPath: data.endpoint
