apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: foo
spec:
  forProvider:
    manifest:
      apiVersion: v1
      data:
        sample-key: sample-value
      kind: ConfigMap
      metadata:
        namespace: default
  providerConfigRef:
    name: provider-kubernetes
  references:
    - patchesFrom:
        apiVersion: memorydb.aws.upbound.io/v1beta1
        fieldPath: data.sample-key-from-bar
        kind: Cluster
        name: memorydb-cross-instance
        namespace: default
