apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
   name: provider-k8s
spec:
   package: xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.7.0
   controllerConfigRef:
      name: irsa-controllerconfig
