apiVersion: aws.database.example.org/v1alpha1
kind: CrossplanePG
metadata:
  name: crossplane-pg
spec:
  storageGB: 20
  databaseName: mydb
  subnetIds:
   - subnet-0f4624b991eab373d
   - subnet-0d226f23e39186ce4
   - subnet-07daafbc7b27d6383
  region: us-east-2
  vpcId: vpc-011214b27e95562dc
  port: 5432
  cidrBlocks: 
   - "10.40.0.0/16"
  engine: postgres
  engineVersion: "13.7"
  instanceClass: "db.t3.micro"
  passwordSecret:  db-creds
  connectionInfoSecret: db-creds-out
  namespace: default
  storageType: gp2
  username: adminer
  resourceConfig:
    providerConfigName: default 
