apiVersion: aws.database.example.org/v1alpha1
kind: CrossplanePG
metadata:
  name: crossplane-pg
spec:
  storageGB: 20
  databaseName: mydb
  subnetIds:
   - subnet-069d1f7af36af5805
   - subnet-0a299a68711fa9bf1
   - subnet-0390461672822b765
  region: us-east-2
  vpcId: vpc-0394aecf1a99670d0
  port: 5432
  cidrBlocks: 
   - "10.40.0.0/16"
  engine: postgres
  engineVersion: "13.7"
  instanceClass: "db.t3.micro"
  passwordSecret:  db-creds
  connectionInfoSecret: db-creds-out
  namespace: mydb
  storageType: gp2
  username: adminer
  resourceConfig:
    providerConfigName: default 
