apiVersion: rds.aws.upbound.io/v1beta1
kind: SubnetGroup
metadata:
  name: example-subnetgroup
spec:
  providerConfigRef:
    name: default
  forProvider:
    region: us-east-2
    subnetIds: 
      - subnet-06f5806b19381cb3e
      - subnet-03c0ee65d5fba9b97
      - subnet-0023e1e93fdfc6b5d
    tags:
      Name: My DB subnet group
