apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcrossplanememorydbs.aws.database.example.org
spec:
  defaultCompositionRef: 
    name: xmemorydb.aws.database.example.org
  group: aws.database.example.org
  names:
    kind: XCrossplaneMemoryDB
    plural: xcrossplanememorydbs
  claimNames:
    kind: CrossplaneMemoryDB
    plural: crossplanememorydbs
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              type: object
              properties:
                subnetIds: 
                  type: array
                  items: 
                    type: string
                region:
                  type: string
                cidrBlocks:
                  type: array
                  items: 
                    type: string
                namespace:
                  type: string
                port:
                  type: number
                instanceClass:
                  type: string
                connectionInfoSecret:
                  type: string
                resourceConfig:
                  type: object
                  description: ResourceConfig defines general properties of this AWS resource.
                  properties:
                    providerConfigName:
                      type: string
              required:
                - region
                - port
                - namespace
                - cidrBlocks
                - subnetIds
                - instanceClass
                - connectionInfoSecret
