apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcrossplanepgs.aws.database.example.org
spec:
  defaultCompositionRef: 
    name: rds-postgres.aws.database.example.org
  group: aws.database.example.org
  names:
    kind: XCrossplanePG
    plural: xcrossplanepgs
  claimNames:
    kind: CrossplanePG
    plural: crossplanepgs
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              type: object
              properties:
                databaseName:
                  type: string
                storageGB:
                  type: integer
                storageType:
                  type: string
                subnetIds: 
                  type: array
                  items: 
                    type: string
                region:
                  type: string
                vpcId: 
                  type: string
                port:
                  type: number
                cidrBlocks:
                  type: array
                  items: 
                    type: string
                engine:
                  type: string
                engineVersion:
                  type: string
                instanceClass:
                  type: string
                username:
                  type: string
                passwordSecret:
                  type: string
                connectionInfoSecret:
                  type: string
                namespace:
                  type: string
                resourceConfig:
                  type: object
                  description: ResourceConfig defines general properties of this AWS resource.
                  properties:
                    providerConfigName:
                      type: string
              required:
                - databaseName
                - storageGB
                - storageType
                - region
                - vpcId
                - port
                - engine
                - engineVersion
                - instanceClass
                - username
                - passwordSecret
                - connectionInfoSecret
                - namespace
                - cidrBlocks
                - subnetIds
