apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcrossplaneapgsserverless.aws.database.example.org
spec:
  defaultCompositionRef: 
    name: apg-serverless.aws.database.example.org
  group: aws.database.example.org
  names:
    kind: XCrossplaneAPGServerless
    plural: xcrossplaneapgsserverless
  claimNames:
    kind: CrossplaneAPGServerless
    plural: crossplaneapgsserverless
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              type: object
              properties:
                databaseName:
                  type: string
                subnetIds: 
                  type: array
                  items: 
                    type: string
                region:
                  type: string
                vpcId: 
                  type: string
                cidrBlocks:
                  type: array
                  items: 
                    type: string
                engine:
                  type: string
                engineVersion:
                  type: string
                minCapacity:
                  type: number
                serverlessv2ScalingConfiguration:
                  type: array
                  items:
                    type: object
                    properties:
                      minCapacity:
                        type: number
                      maxCapacity:
                        type: number
                maxCapacity:
                  type: number
                masterUsername:
                  type: string
                masterPasswordSecret:
                  type: string
                connectionInfoSecret:
                  type: string
                namespace:
                  type: string
                port:
                  type: number
                instanceClass:
                  type: string
                resourceConfig:
                  type: object
                  description: ResourceConfig defines general properties of this AWS resource.
                  properties:
                    providerConfigName:
                      type: string
              required:
                - databaseName
                - region
                - vpcId
                - engine
                - engineVersion
                - port
                - minCapacity
                - maxCapacity
                - masterUsername
                - masterPasswordSecret
                - connectionInfoSecret
                - namespace
                - cidrBlocks
                - subnetIds
                - instanceClass

---

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: apg-serverless.aws.database.example.org
spec:
  compositeTypeRef:
    apiVersion: aws.database.example.org/v1alpha1
    kind: XCrossplaneAPGServerless
  patchSets:
    - name: common-fields
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.providerConfigName
          toFieldPath: spec.providerConfigRef.name
  resources:
    - base:
        apiVersion: rds.aws.upbound.io/v1beta1
        kind: SubnetGroup
        spec:
          providerConfigRef:
            name: to-be-patched
          forProvider:
            name: aurora-subnet-name
            region: to-be-patched
            description: "aurora-postgresql-subnet"
            subnetIds: to-be-patched
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.subnetIds"
          toFieldPath: "spec.forProvider.subnetIds"
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroup
        spec:
         providerConfigRef:
            name: to-be-patched
         forProvider:
            name: aurora-sg
            region: to-be-patched
            vpcId: to-be-patched
            description: "aurora-pg-sg"
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.vpcId"
          toFieldPath: "spec.forProvider.vpcId"
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.forProvider.groupName"
          transforms:
            - type: string
              string:
                fmt: "aurora-sg-%s"
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroupRule
        metadata:
           name: aurora-sg-rule1
        spec:
         providerConfigRef:
           name: to-be-patched
         forProvider:
           cidrBlocks: to-be-patched
           fromPort: to-be-patched
           protocol: tcp
           region: to-be-patched
           securityGroupIdSelector:
              matchControllerRef: true
           toPort: to-be-patched
           type: ingress
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.port"
          toFieldPath: "spec.forProvider.fromPort"
        - fromFieldPath: "spec.port"
          toFieldPath: "spec.forProvider.toPort"
        - fromFieldPath: "spec.cidrBlocks"
          toFieldPath: "spec.forProvider.cidrBlocks"
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroupRule
        metadata:
           name: comp-aurora-sg-rule2
        spec:
         forProvider:
           cidrBlocks:
             - "0.0.0.0/0"
           fromPort: 0
           protocol: tcp
           region: to-be-patched
           securityGroupIdSelector:
              matchControllerRef: true
           toPort: 0
           type: egress
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
    - base:
        apiVersion: rds.aws.upbound.io/v1beta1
        kind: Cluster
        metadata:
          annotations:
            upjet.upbound.io/manual-intervention: This resource has a password secret reference.
          name: aurora-cross-instance
          namespace: default
        spec:
          providerConfigRef:
            name: to-be-patched
          forProvider:
             dbSubnetGroupNameSelector:
                matchControllerRef: true
             vpcSecurityGroupIdSelector:
                matchControllerRef: true
             engine: to-be-patched
             engineVersion: to-be-patched
             port: to-be-patched
             skipFinalSnapshot: true
             masterUsername: to-be-patched
             serverlessv2ScalingConfiguration: 
               - minCapacity: to-be-patched
                 maxCapacity: to-be-patched
             masterPasswordSecretRef:
               key: password
               name: to-be-patched
               namespace: to-be-patched
             region: to-be-patched
          writeConnectionSecretToRef:
            namespace: to-be-patched
            name: to-be-patched
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - fromFieldPath: "spec.engine"
          toFieldPath: "spec.forProvider.engine"
        - fromFieldPath: "spec.port"
          toFieldPath: "spec.forProvider.port"
        - fromFieldPath: "spec.engineVersion"
          toFieldPath: "spec.forProvider.engineVersion"
        - fromFieldPath: "spec.masterPasswordSecret"
          toFieldPath: "spec.forProvider.masterPasswordSecretRef.name"
        - fromFieldPath: "spec.namespace"
          toFieldPath: "spec.forProvider.masterPasswordSecretRef.namespace"
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.namespace"
          toFieldPath: "spec.forProvider.namespace"
        - fromFieldPath: "spec.connectionInfoSecret"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
        - fromFieldPath: "spec.namespace"
          toFieldPath: "spec.writeConnectionSecretToRef.namespace"
        - fromFieldPath: "spec.masterUsername"
          toFieldPath: "spec.forProvider.masterUsername"
        - fromFieldPath: "spec.minCapacity"
          toFieldPath: "spec.forProvider.serverlessv2ScalingConfiguration[0].minCapacity"
        - fromFieldPath: "spec.maxCapacity"
          toFieldPath: "spec.forProvider.serverlessv2ScalingConfiguration[0].maxCapacity"
      connectionDetails:
        - name: username
          fromFieldPath: spec.forProvider.username
        - name: password
          fromConnectionSecretKey: attribute.password
        - name: endpoint
          fromFieldPath: status.atProvider.endpoint
    - base:
        apiVersion: rds.aws.upbound.io/v1beta1
        kind: ClusterInstance
        metadata:
          annotations:
            upjet.upbound.io/manual-intervention: This resource has a password secret reference.
          name: aurora-cross-instance
          namespace: default
        spec:
          providerConfigRef:
            name: to-be-patched
          forProvider:
             clusterIdentifierSelector:
               matchControllerRef: true
             instanceClass: to-be-patched
             engine: to-be-patched
             region: to-be-patched
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - fromFieldPath: "spec.engine"
          toFieldPath: "spec.forProvider.engine"
        - fromFieldPath: "spec.instanceClass"
          toFieldPath: "spec.forProvider.instanceClass"
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"

