apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: upbound-system
resources:
  - namespace.yaml
  - crossplane-serviceaccount.yaml
  - aurora-crd-composition.yaml
  - memorydb-crd-compsition.yaml
