apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xcrossplanememorydbs.aws.database.example.org
spec:
  defaultCompositionRef: 
    name: xmemorydb.aws.database.example.org
  group: aws.database.example.org
  names:
    kind: XCrossplaneMemoryDB
    plural: xcrossplanememorydbs
  claimNames:
    kind: CrossplaneMemoryDB
    plural: crossplanememorydbs
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          properties:
            spec:
              type: object
              properties:
                subnetIds: 
                  type: array
                  items: 
                    type: string
                region:
                  type: string
                cidrBlocks:
                  type: array
                  items: 
                    type: string
                namespace:
                  type: string
                name:
                  type: string
                port:
                  type: number
                instanceClass:
                  type: string
                vpcId:
                  type: string
                connectionInfoSecret:
                  type: string
                connectionInfoCM:
                  type: string
                resourceConfig:
                  type: object
                  description: ResourceConfig defines general properties of this AWS resource.
                  properties:
                    providerConfigName:
                      type: string
              required:
                - region
                - port
                - namespace
                - name
                - cidrBlocks
                - subnetIds
                - instanceClass
                - connectionInfoSecret
                - connectionInfoCM

--- 

apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xmemorydb.aws.database.example.org
spec:
  compositeTypeRef:
    apiVersion: aws.database.example.org/v1alpha1
    kind: XCrossplaneMemoryDB
  patchSets:
    - name: common-fields
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.resourceConfig.providerConfigName
          toFieldPath: spec.providerConfigRef.name
  resources:
    - base:
        apiVersion: memorydb.aws.upbound.io/v1beta1
        kind: SubnetGroup
        spec:
          providerConfigRef:
            name: to-be-patched
          forProvider:
            name: memorydb-subnet-name
            region: to-be-patched
            description: "memorydb-subnet"
            subnetIds: to-be-patched
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.subnetIds"
          toFieldPath: "spec.forProvider.subnetIds"
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroup
        spec:
         providerConfigRef:
            name: to-be-patched
         forProvider:
            name: memorydb-sg
            region: to-be-patched
            vpcId: to-be-patched
            description: "memorydb-sg"
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.vpcId"
          toFieldPath: "spec.forProvider.vpcId"
        - fromFieldPath: "metadata.uid"
          toFieldPath: "spec.forProvider.groupName"
          transforms:
            - type: string
              string:
                fmt: "memorydb-sg-%s"
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroupRule
        metadata:
           name: memorydb-sg-rule1
        spec:
         providerConfigRef:
           name: to-be-patched
         forProvider:
           cidrBlocks: to-be-patched
           fromPort: to-be-patched
           protocol: tcp
           region: to-be-patched
           securityGroupIdSelector:
              matchControllerRef: true
           toPort: to-be-patched
           type: ingress
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.port"
          toFieldPath: "spec.forProvider.fromPort"
        - fromFieldPath: "spec.port"
          toFieldPath: "spec.forProvider.toPort"
        - fromFieldPath: "spec.cidrBlocks"
          toFieldPath: "spec.forProvider.cidrBlocks"
    - base:
        apiVersion: ec2.aws.upbound.io/v1beta1
        kind: SecurityGroupRule
        metadata:
           name: memorydb-sg-rule2
        spec:
         forProvider:
           cidrBlocks:
             - "0.0.0.0/0"
           fromPort: 0
           protocol: tcp
           region: to-be-patched
           securityGroupIdSelector:
              matchControllerRef: true
           toPort: 0
           type: egress
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
    - base:
        apiVersion: memorydb.aws.upbound.io/v1beta1
        kind: Cluster
        metadata:
          annotations:
            upjet.upbound.io/manual-intervention: This resource has a password secret reference.
          name: to-be-patched
          namespace: to-be-patched
        spec:
          providerConfigRef:
            name: to-be-patched
          forProvider:
             aclName: open-access
             dbSubnetGroupNameSelector:
                matchControllerRef: true
             vpcSecurityGroupIdSelector:
                matchControllerRef: true
             port: to-be-patched
             region: to-be-patched
             nodeType: to-be-patched
          writeConnectionSecretToRef:
            namespace: to-be-patched
            name: to-be-patched
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - fromFieldPath: "spec.port"
          toFieldPath: "spec.forProvider.port"
        - fromFieldPath: "spec.name"
          toFieldPath: "metadata.name"
        - fromFieldPath: "spec.namespace"
          toFieldPath: "spec.forProvider.masterPasswordSecretRef.namespace"
        - fromFieldPath: "spec.region"
          toFieldPath: "spec.forProvider.region"
        - fromFieldPath: "spec.namespace"
          toFieldPath: "metadata.namespace"
        - fromFieldPath: "spec.namespace"
          toFieldPath: "spec.writeConnectionSecretToRef.namespace"
        - fromFieldPath: "spec.connectionInfoSecret"
          toFieldPath: "spec.writeConnectionSecretToRef.name"
        - fromFieldPath: "spec.instanceClass"
          toFieldPath: "spec.forProvider.nodeType"
      connectionDetails:
        - name: port
          fromFieldPath: spec.forProvider.port
        - name: username
          fromFieldPath: spec.forProvider.username
        - name: password
          fromConnectionSecretKey: attribute.password
        - name: endpoint
          fromFieldPath: status.atProvider.endpoint

    - base: 
          apiVersion: kubernetes.crossplane.io/v1alpha1
          kind: Object
          metadata:
            name: to-be-patched
          spec:
            forProvider:
               manifest:
                  apiVersion: v1
                  data:
                     memorydb-cluster-host: to-be-patched
                  kind: ConfigMap
                  metadata:
                    namespace: to-be-patched 
            providerConfigRef:
              name: provider-kubernetes
            references:
              - patchesFrom:
                   apiVersion: memorydb.aws.upbound.io/v1beta1
                   fieldPath: data.memorydb-cluster-host
                   kind: Cluster
                   name: memorydb-cross-instance
                   namespace: to-be-patched
      patches:
        - type: PatchSet
          patchSetName: common-fields
        - fromFieldPath: "spec.namespace"
          toFieldPath: "spec.forProvider.manifest.metadata.namespace"
        - fromFieldPath: "spec.namespace"
          toFieldPath: "spec.references[0].patchesFrom.namespace"
        - fromFieldPath: "spec.connectionInfoCM"
          toFieldPath: "metadata.name"
